name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 4 * * 2'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc # v3.6.0
      with:
        java-version: 8
        distribution: temurin
    - uses: coursier/cache-action@v6
    - run: sbt "+scalafmtCheckAll" scalafmtSbtCheck "+test"
